In [1]:
import numpy as np
from __future__ import division#これがないとpy2だと5/2=2となってしまう^^;

In [ ]:
#これから分散の解説をpythonコーディングを含めて解説していきます^^
#分散は、「データがどのくらいばらつきがあるか」を示すために考えられた指標です。
#とりあえず計算して色々なデータ同士のばらつきの大きさを比較すると分散の便利さが実感できると思います。

In [4]:
#ある国Xの適当に声をかけた人５人の所持金（単位：ドル）とするとき、(5ドル、２４ドル、５４ドル、１４ドル、２４ドル)であった。
arr_1 = np.array([[5],[24],[54],[14],[24]])
arr_1

array([[ 5],
       [24],
       [54],
       [14],
       [24]])

In [5]:
#分散は{（データの値-平均値）＾２＋・・・＋（データの値-平均値）＾２}÷データの個数　です。

#平均を引く理由：データを平均値を基準としてどのくらい離れてるかを計算するため
#２乗する理由：データの値-平均値の全データをそのまま足すと、合計0になってしまい、はなれている距離の計算ができなくなるので、
#２乗することで、相対距離が示せるように工夫されているというわけです（問題点：単位は今回の場合だとドルなはずですが、分散はドル^2という謎の単位になってしまう）

In [6]:
#では、分散を出しましょう
np.var(arr_1)  

272.15999999999997

In [7]:
#272・・・とでました、これだけだと何も役立ちません。ということで、比べる対象を用意します。
#ある配給制の国Yの適当に声をかけた人５人の所持金（単位：ドル）とする）とするとき、(10ドル、10ドル、10ドル、11ドル、12ドル)であった。と、します。
arr_2 = np.array([[10],[10],[10],[11],[12]])
arr_2

array([[10],
       [10],
       [10],
       [11],
       [12]])

In [8]:
#では、分散を出しましょう
np.var(arr_2)  

0.64000000000000001

In [9]:
#0.64ですね。ここでようやく分散が役立ちます。
#ある国Xの適当に声をかけた人５人の所持金（単位：ドル）のばらつき度（分散）は、約272
#ある国Yの適当に声をかけた人５人の所持金（単位：ドル）のばらつき度（分散）は、約0.64
#ある国Yは配給制なので、さすがにばらつきは小さいなぁ　という感想くらいは科学的に言えるようになりました^^

In [10]:
#ところで、分散について（問題点：単位は今回の場合だとドルなはずですが、分散はドル^2という謎の単位になってしまう）ということがありましたね、
#これを解決できると、よりよいですよね？どうするか？、平方根とればドル^２がドルに戻りますよね、というわけです、これが標準偏差です。
#では２国のアンケート結果の標準偏差を求めましょう

In [11]:
np.std(arr_1) 

16.497272501841024

In [12]:
np.std(arr_2) 

0.80000000000000004

In [13]:
#これらを比較すればいいことになります。

In [14]:
#では、今までは分散、標準偏差と、調査対象がひとつの数の集まりについてに限定されていました。
#でも、例えばある国Xとある国Yの所持金アンケートの結果はお互い関係があるかどうかも知ると便利かもしれませんよね？
#そこで、そんな２つの数字のグループを対象とした調査をしたい人のために、共分散という概念が作られました。

In [15]:
#共分散の考え方は、あるグループの数からとりあえず平均値を出して差し引いておきます。
#先ほどのある国XとYの話でも平均値を基準にするために得られた値から平均値を取り除いたのと同じコンセプトです。まあやってみましょう。

In [17]:
arr_1 = np.array([[5],[24],[54],[14],[24]])
arr_1_mean = arr_1.mean()
arr_1_mean

24.199999999999999

In [43]:
arr_1_meandrop = np.array([])
for i in arr_1:
    g = i - arr_1_mean
    arr_1_meandrop = np.append(arr_1_meandrop, g)
arr_1_meandrop

array([-19.2,  -0.2,  29.8, -10.2,  -0.2])

In [44]:
 #ある国Xの所持金アンケート結果から平均値をとったアレイになりました。では続けてある国Yの所持金アンケートから平均値をとったアレイを作りましょう

In [45]:
arr_2 = np.array([[10],[10],[10],[11],[12]])
arr_2_mean = arr_2.mean()
arr_2_mean

10.6

In [46]:
arr_2_meandrop = np.array([])
for j in arr_2:
    h = j - arr_2_mean
    arr_2_meandrop = np.append(arr_2_meandrop, h)
arr_2_meandrop

array([-0.6, -0.6, -0.6,  0.4,  1.4])

In [47]:
#ある国Yの所持金アンケート結果から平均値をとったアレイになりました。
#さて、これをちょっと見てみましょう。ぱっと見ですけれども、
#ある国X:array([-19.2,  -0.2,  29.8, -10.2,  -0.2])
#ある国Y:array([-0.6, -0.6, -0.6,  0.4,  1.4])
#ある国XとYはXの所持金が多くなっても、少なくなってもなんだか連動しなさそうですね・・・^^;これでは、共分散便利ということにはなりません。
#と、いうわけでさらにもうひとつ架空の国を作りましょう

In [48]:
#ある国Zの適当に声をかけた人５人の所持金（単位：ドル）とするとき、(100ドル、２00ドル、５00ドル、１４0ドル、50ドル)であった。
#と、しましょう。
#念のため平均値、分散、標準偏差を求めておきましょう

In [49]:
arr_3 = np.array([[100],[200],[500],[140],[50]])
arr_3_mean = arr_3.mean()
arr_3_mean

198.0

In [52]:
np.var(arr_3) 

25216.0

In [53]:
np.std(arr_3) 

158.79546593023366

In [54]:
#国Zは他の国と比べて大分貧富の差がある感じになりましたね^^;
#では、ある国Zの所持金アンケート結果から平均値をとったアレイも計算してみましょう

In [56]:
arr_3_meandrop = np.array([])
for k in arr_3:
    l = k - arr_3_mean
    arr_3_meandrop = np.append(arr_3_meandrop, l)
arr_3_meandrop

array([ -98.,    2.,  302.,  -58., -148.])

In [57]:
#さて、これをちょっと見てみましょう。ぱっと見ですけれども、
#ある国X:array([-19.2,  -0.2,  29.8, -10.2,  -0.2])
#ある国Y:array([-0.6, -0.6, -0.6,  0.4,  1.4])
#ある国Z:aarray([ -98.,    2.,  302.,  -58., -148.])
#ある国XとZを比べてみると、なんだか関係ありそうな感じはしますね、つまり、X:-19.2のとき対応要素はZ:-98,
#X:-０．２（ちょっと平均値近づくと）のとき対応要素はZ:-２(Zもかなり近づきましたね)
#X:２９．８（ぐっとあがった）のとき対応要素はZ:３０２（こちらもぐっとあがった）、
#この関係性を数値で示したい、そんなときは、対応する要素をかけてしまって、そのかけたもののトータルが大きければ大きいほど、連動してるよねと言える
#（２つのグループの対応要素が互いにマイナスの値の場合はかけると、正。お互い正の値の場合もかけると正　になる　＝　同じ方向への連動しているポイントアップ）
#(２つのグループの対応要素の符合が違うと、かけたらマイナスの値になるので逆方向に連動しているポイントアップという意味になる
#と、いうわけで共分散は、（グループ１の対応要素の値-平均）×（グループ２の対応要素の値-平均）を一個一個たしていく（今回の場合はデータが５個ずつなので５回）
#さらに、数値の個数でわる（今回は５。理由は、他の分析したグループの共分散の値と比較できるから）　ということででてきます。

#参考になりそうなリンク
#http://emoson.hateblo.jp/entry/2014/10/26/133736

#数式で書くと、
#Cov(X,Y)=E[(X−μX)(Y−μY)]
#Cov(X,Y)：データXとデータYの共分散という意味
#E[〜]：〜内の期待値（＝平均）つまり、データの個数で割ってくれということ
#(X−μX)：データXの値を平均μXから引いた値
#(Y−μY)：データYの値を平均μYから引いた値
#(X−μX)(Y−μY)：データXの値を平均μXから引いた値とデータYの値を平均μYから引いた値をかけた値
#E[(X−μX)(Y−μY)]データXの値を平均μXから引いた値とデータYの値を平均μYから引いた値をかけた値をデータのセットの個数で割った値（＝共分散）
#と、なる

In [58]:
#さて、計算してみよ〜^o^/

In [59]:
np.cov(arr_1_meandrop, arr_3_meandrop)

array([[   340.2,   2875.5],
       [  2875.5,  31520. ]])

In [63]:
#2875.5ですね、
#numpyのcovメソッドは、分散共分散行列で返ってくるため、340.2はarr_1_meandropの分散、３１５２０は、arr_３_meandropの分散となっています。
#この分散共分散行列は統計学的にあとあと処理しやすい（例えば、複数グループの共分散を一気に比較できる）ので、numpyは考慮されているということです。

In [64]:
#でも、なんかしらないけど、３次元はできないっぽい　こういうの：np.cov(arr_1_meandrop, arr_2_meandrop, arr_3_meandrop)
#SciKit-Learnでできるようだ・・・

In [ ]:
#おしまい^^